name: calculator
description: A calculator to perform simple mathematical expressions.
publish_to: 'none'
version: 2.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  math_expressions: ^2.1.0
  toast: ^0.1.5
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  shared_preferences: ^2.0.5
  yaml: ^3.1.0
  file_picker: ^3.0.0
  package_info: ^2.0.0
  page_transition: ^1.1.7+6
  provider: ^5.0.0
  json2yaml: ^1.0.1+1
  cached_network_image: ^3.0.0-nullsafety

dev_dependencies:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: assets/icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true